### ISSUE TITLE
Cannot dual panelify (Argument Missing, Permission Denied)

### ISSUE THREAD

**Issue by devolskii** [ahrm/sioyek-python-extensions#16]
I installed using `yay sioyek`, using Arch Linux.

I run **sioyek** from terminal.

I see the following messages in terminal.

`QString::arg: Argument missing: python -m sioyek.dual_panelify "%{sioyek_path}" "%{file_path}" "%{command_text}", /usr/share/sioyek/tutorial.pdf
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/devolskii/.local/lib/python3.11/site-packages/sioyek/dual_panelify.py", line 149, in <module>
    with open(dual_panel_file_path, 'wb') as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: '/usr/share/sioyek/tutorial_dual_panel.pdf'`

**Comment by ahrm** [comment]
I think that extension tries to create the dual panel version right next to the original file. It seems like the sioyek's tutorial path is not writable in this package, so it can't create it. It probably will work with some other file in a writeable path.
